### PR TITLE
CASMINST-6731: Switch admin password is no longer needed for CSM 1.5+

### PR DESCRIPTION
**Pull request by mharding-hpe**
## Summary and Scope

Goss tests no longer need the switch admin password set using an environment variable. The tests read the value directly from Vault now. 

The following PRs updated `docs-csm` to reflect this:
* https://github.com/Cray-HPE/docs-csm/pull/4540
* https://github.com/Cray-HPE/docs-csm/pull/4541

This PR does the same for `cray-nls`

### CODE REVIEW

**Comment by mharding-hpe** [comment]
> > Is this changing the API in a non-backwards compatible way? If so, is it really necessary to fully remove it?
> 
> It isn't necessary to remove it the parameter. The important things are:
> 
>     1. Our workflows to no longer specify that parameter
> 
>     2. If a workflow does not specify the parameter, the environment variable should not be set at all (rather than having it get set to an empty value)
> 
> 
> That seemed like a more complicated change than removing the parameter, and since I am not a NLS expert, that's why I opted for it. But if someone wants to make an alternative PR to accomplish the above two things, I'd be delighted by that instead.

**Comment by mharding-hpe** [comment]
I am going to close this PR and instead handle this work in two different Jiras. I'll use this current Jira just to make changes to docs-csm which do not make any assumptions about NLS/IUF being changed.

I will open a second Jira to do the NLS/IUF portion, and hopefully an NLS/IUF developer can take that piece.

**Comment by mharding-hpe** [comment]
@atifsyedali @haasken-hpe I have opened https://jira-pro.it.hpe.com:8443/browse/CASMINST-6734 so that someone with more IUF/NLS knowledge can make the changes to reflect that the switch admin password environment variable should not be required or set.

**Comment by haasken-hpe** [comment]
> @atifsyedali @haasken-hpe I have opened https://jira-pro.it.hpe.com:8443/browse/CASMINST-6734 so that someone with more IUF/NLS knowledge can make the changes to reflect that the switch admin password environment variable should not be required or set.

Thanks, @mharding-hpe. I'm not the expert in this area either. I just saw what appeared to be the removal of a parameter from the API, and I thought it could cause backwards compatibility issues.

**Pull request closed without merging**
